/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.NotaDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Nota;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class frmEstudiantesAprovados extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEstudiantesAprovados
     */
    NotaDao notaDao = new NotaDao();

    public frmEstudiantesAprovados() {
        initComponents();
        listarEstudantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosN = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rdAprobado = new javax.swing.JRadioButton();
        rdSuple = new javax.swing.JRadioButton();
        btnFilter = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tblDatosN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estudiante", "Apellido", "Nota"
            }
        ));
        jScrollPane1.setViewportView(tblDatosN);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        rdAprobado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdAprobado);
        rdAprobado.setForeground(new java.awt.Color(0, 0, 0));
        rdAprobado.setText("Aprobado");

        rdSuple.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdSuple);
        rdSuple.setForeground(new java.awt.Color(0, 0, 0));
        rdSuple.setText("Supletorio");

        btnFilter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(0, 0, 0));
        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/findFilter.png"))); // NOI18N
        btnFilter.setText("Filtrar");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rdAprobado)
                .addGap(84, 84, 84)
                .addComponent(rdSuple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnFilter)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAprobado)
                    .addComponent(rdSuple)
                    .addComponent(btnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(556, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        if (rdAprobado.isSelected()) {
            listarEstudantesAprobados(7);
        }
        if (rdSuple.isSelected()) {
            listarEstudantesNoAprobados(6);
        }

    }//GEN-LAST:event_btnFilterActionPerformed

    public void listarEstudantes() {
        DefaultTableModel dtm = (DefaultTableModel) tblDatosN.getModel();
        List<Nota> nota = notaDao.listarEstudiante();
        dtm.setRowCount(0);
        for (Nota n : nota) {
            Object[] fila = new Object[]{n.getNombre(), n.getApellido(), n.getNota()};
            dtm.addRow(fila);
        }
    }

    public void listarEstudantesAprobados(int numero) {
        DefaultTableModel dtm = (DefaultTableModel) tblDatosN.getModel();
        List<Nota> nota = notaDao.listarEstudinatesAprobados(numero);
        dtm.setRowCount(0);
        for (Nota n : nota) {
            Object[] fila = new Object[]{n.getNombre(), n.getApellido(), n.getNota()};
            dtm.addRow(fila);
        }
    }

    public void listarEstudantesNoAprobados(int numero) {
        DefaultTableModel dtm = (DefaultTableModel) tblDatosN.getModel();
        List<Nota> nota = notaDao.listarEstudinatesNoAprobados(numero);
        dtm.setRowCount(0);
        for (Nota n : nota) {
            Object[] fila = new Object[]{n.getNombre(), n.getApellido(), n.getNota()};
            dtm.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdAprobado;
    private javax.swing.JRadioButton rdSuple;
    private javax.swing.JTable tblDatosN;
    // End of variables declaration//GEN-END:variables
}
