/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CursoDao;
import controlador.EstudianteDao;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.Curso;
import modelo.Estudiante;
import modelo.FechaJdate;

public class frmRegistroEstudiante extends javax.swing.JInternalFrame {

    FechaJdate setearFecha = new FechaJdate();
    //DocenteDao listarD = new DocenteDao();
    CursoDao cursoDao = new CursoDao();
    EstudianteDao nuevoEstu = new EstudianteDao();
    LimpiarCampos lp = new LimpiarCampos();
    int id;

    public frmRegistroEstudiante() {
        initComponents();
        cursoDao.listarCombo(cmbCurso);
        listarEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreE = new javax.swing.JTextField();
        txtApellidoE = new javax.swing.JTextField();
        txtCedulaE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEdadE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbGeneroE = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionE = new javax.swing.JTextField();
        txtTelefonoE = new javax.swing.JTextField();
        bntGuardarE = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosE = new javax.swing.JTable();
        btnActualizarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnNuevoE = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Apellido:");

        txtCedulaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaEKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Edad:");

        txtEdadE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadEKeyTyped(evt);
            }
        });

        jLabel7.setText("Curso:");

        jLabel8.setText("Genero:");

        cmbGeneroE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedulaE)
                    .addComponent(txtNombreE)
                    .addComponent(cmbCurso, 0, 119, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEdadE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellidoE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbGeneroE, 0, 196, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbGeneroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contactos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel6.setText("Telefono:");

        jLabel5.setText("Direccion:");

        txtDireccionE.setToolTipText("");

        txtTelefonoE.setToolTipText("");
        txtTelefonoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoEKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionE)
                    .addComponent(txtTelefonoE, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bntGuardarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/save.png"))); // NOI18N
        bntGuardarE.setText("Guardar");
        bntGuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarEActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.BorderLayout());

        tblDatosE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Cedula", "Direccion", "Telefono", "Edad", "Genero", "Nivel"
            }
        ));
        tblDatosE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatosE);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnActualizarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/update.png"))); // NOI18N
        btnActualizarE.setText("Actualizar");
        btnActualizarE.setEnabled(false);
        btnActualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEActionPerformed(evt);
            }
        });

        btnEliminarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/delete.png"))); // NOI18N
        btnEliminarE.setText("Eliminar");
        btnEliminarE.setEnabled(false);
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        btnNuevoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/newPerson.png"))); // NOI18N
        btnNuevoE.setText("Nuevo");
        btnNuevoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntGuardarE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarE)
                    .addComponent(bntGuardarE)
                    .addComponent(btnEliminarE)
                    .addComponent(btnNuevoE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoEKeyTyped
        // TODO add your handling code here:
        validarNumeros(evt, txtTelefonoE);

    }//GEN-LAST:event_txtTelefonoEKeyTyped

    private void bntGuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarEActionPerformed

        if (txtNombreE.getText().isEmpty() || txtApellidoE.getText().isEmpty() || txtCedulaE.getText().isEmpty()
                || txtEdadE.getText().isEmpty() || cmbGeneroE.getSelectedItem().toString().isEmpty()
                || txtDireccionE.getText().isEmpty() || txtTelefonoE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos..");
        } else {
            int idCurso = cmbCurso.getItemAt(cmbCurso.getSelectedIndex()).getIdCurso();
            String nombre = txtNombreE.getText();
            String apellido = txtApellidoE.getText();
            String cedula = txtCedulaE.getText();
            int edad = Integer.parseInt(txtEdadE.getText());
            String genero = (String) cmbGeneroE.getSelectedItem();
            String direccion = txtDireccionE.getText();
            String telefono = txtTelefonoE.getText();
            Estudiante est = new Estudiante(idCurso, nombre, apellido, cedula, telefono, direccion, edad, genero);
            int estu = nuevoEstu.registroEstudiante(est);
            if (estu > 0) {
                listarEstudiantes();
                lp.limpiarCamposTexto(jPanel3);
                lp.limpiarCamposTexto(jPanel4);

            }
        }


    }//GEN-LAST:event_bntGuardarEActionPerformed

    private void listarEstudiantes() {
        DefaultTableModel dtm = (DefaultTableModel) tblDatosE.getModel();
        List<Estudiante> lista = nuevoEstu.listarEstudiantes();
        dtm.setRowCount(0);
        for (Estudiante estudiente : lista) {
            Object[] fila = new Object[]{estudiente.getIdEstdiante(), estudiente.getNombre(),
                estudiente.getApellido(), estudiente.getCedula(), estudiente.getDireccion(), estudiente.getTelefono(),
                estudiente.getEdad(), estudiente.getSexo(),estudiente.getIdCurso()};
            dtm.addRow(fila);
        }
    }

    private void txtEdadEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadEKeyTyped

        char caracter = evt.getKeyChar();

        if (Character.isLetter(caracter)) {
            getToolkit().beep();
            evt.consume();
        } else if (txtEdadE.getText().length() == 2) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtEdadEKeyTyped

    private void txtCedulaEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaEKeyTyped
        validarNumeros(evt, txtCedulaE);
    }//GEN-LAST:event_txtCedulaEKeyTyped

    private void btnActualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEActionPerformed

        if (id != 0) {//id con valor
            String nombre = txtNombreE.getText();
            String apellido = txtApellidoE.getText();
            String cedula = txtCedulaE.getText();
            String direccion = txtDireccionE.getText();
            String telefono = txtTelefonoE.getText();
            int edad = Integer.parseInt(txtEdadE.getText());
            int idCurso = cmbCurso.getItemAt(cmbCurso.getSelectedIndex()).getIdCurso();
            String genero = String.valueOf(cmbGeneroE.getSelectedItem());
            Estudiante update = new Estudiante(id, nombre, apellido, cedula, telefono, direccion, edad, genero);
            int r = nuevoEstu.actualizarEstudiante(update);
            if (r > 0) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados..");
                listarEstudiantes();
                lp.limpiarCamposTexto(jPanel3);
                lp.limpiarCamposTexto(jPanel4);
                bntGuardarE.setEnabled(true);
                btnActualizarE.setEnabled(false);
                btnEliminarE.setEnabled(false);
                id = 0;
            }
            id = 0;
        }

    }//GEN-LAST:event_btnActualizarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        // TODO add your handling code here:
        if (id != 0) {
            int opc = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar '" + txtNombreE.getText() + "'?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                Estudiante eliminar = new Estudiante(id);
                nuevoEstu.eliminarEstudiante(eliminar);
                listarEstudiantes();
                lp.limpiarCamposTexto(jPanel3);
                lp.limpiarCamposTexto(jPanel4);
                id = 0;
            }

        }
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void btnNuevoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEActionPerformed
        // TODO add your handling code here:
        lp.limpiarCamposTexto(jPanel3);
        lp.limpiarCamposTexto(jPanel4);
        btnActualizarE.setEnabled(false);
        btnEliminarE.setEnabled(false);
        bntGuardarE.setEnabled(true);
        id = 0;
    }//GEN-LAST:event_btnNuevoEActionPerformed


    private void tblDatosEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosEMouseClicked
        // TODO add your handling code here:
        if (tblDatosE.getSelectedRowCount() > 0) {
            id = (int) tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 0);
            txtNombreE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 1).toString());
            txtApellidoE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 2).toString());
            txtCedulaE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 3).toString());
            txtDireccionE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 4).toString());
            txtTelefonoE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 5).toString());
            txtEdadE.setText(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 6).toString());
            cmbGeneroE.setSelectedItem(tblDatosE.getValueAt(tblDatosE.getSelectedRow(), 8).toString());
            bntGuardarE.setEnabled(false);
            btnActualizarE.setEnabled(true);
            btnEliminarE.setEnabled(true);
        }

    }//GEN-LAST:event_tblDatosEMouseClicked

    private void validarNumeros(java.awt.event.KeyEvent evt, JTextField txt) {
        char caracter = evt.getKeyChar();

        if (Character.isLetter(caracter)) {
            getToolkit().beep();
            evt.consume();
        } else if (txt.getText().length() == 10) {
            getToolkit().beep();
            evt.consume();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardarE;
    private javax.swing.JButton btnActualizarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnNuevoE;
    private javax.swing.JComboBox<Curso> cmbCurso;
    private javax.swing.JComboBox<String> cmbGeneroE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosE;
    private javax.swing.JTextField txtApellidoE;
    private javax.swing.JTextField txtCedulaE;
    private javax.swing.JTextField txtDireccionE;
    private javax.swing.JTextField txtEdadE;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtTelefonoE;
    // End of variables declaration//GEN-END:variables
}
