/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DocenteDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Docente;
import modelo.FechaJdate;
public class registroDoce extends javax.swing.JInternalFrame {

    int id;
    DocenteDao DocenteDao = new DocenteDao();
    FechaJdate setearFecha = new FechaJdate();
    LimpiarCampos lp = new LimpiarCampos();
    public registroDoce() {
        initComponents();
        listarDocentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        txtApellidoD = new javax.swing.JTextField();
        txtCedulaD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEdadD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbGeneroD = new javax.swing.JComboBox<>();
        cmbTituloD = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionD = new javax.swing.JTextField();
        txtTelefonoD = new javax.swing.JTextField();
        bntGuardarD = new javax.swing.JButton();
        bntActualizarD = new javax.swing.JButton();
        btnEliminarD = new javax.swing.JButton();
        btnNuevoD = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocentes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Docente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Apellido:");

        txtCedulaD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaDKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Edad:");

        txtEdadD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadDKeyTyped(evt);
            }
        });

        jLabel7.setText("Título:");

        jLabel8.setText("Genero:");

        cmbGeneroD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        cmbTituloD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniero/a", "Magíster", "Licenciado/a", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedulaD)
                    .addComponent(txtNombreD)
                    .addComponent(cmbTituloD, 0, 148, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbGeneroD, 0, 147, Short.MAX_VALUE)
                    .addComponent(txtEdadD)
                    .addComponent(txtApellidoD))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtEdadD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cmbTituloD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbGeneroD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contactos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel6.setText("Telefono:");

        jLabel5.setText("Direccion:");

        txtDireccionD.setToolTipText("");

        txtTelefonoD.setToolTipText("");
        txtTelefonoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionD)
                    .addComponent(txtTelefonoD, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bntGuardarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/save.png"))); // NOI18N
        bntGuardarD.setText("Guardar");
        bntGuardarD.setToolTipText("Guardar Registro");
        bntGuardarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarDActionPerformed(evt);
            }
        });

        bntActualizarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/update.png"))); // NOI18N
        bntActualizarD.setText("Actualizar");
        bntActualizarD.setToolTipText("Guardar Registro");
        bntActualizarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActualizarDActionPerformed(evt);
            }
        });

        btnEliminarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/delete.png"))); // NOI18N
        btnEliminarD.setText("Eliminar");
        btnEliminarD.setToolTipText("Guardar Registro");
        btnEliminarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDActionPerformed(evt);
            }
        });

        btnNuevoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcons/newPerson.png"))); // NOI18N
        btnNuevoD.setText("Nuevo");
        btnNuevoD.setToolTipText("Guardar Registro");
        btnNuevoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bntGuardarD)
                        .addGap(24, 24, 24)
                        .addComponent(bntActualizarD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarD)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoD))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntActualizarD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntGuardarD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        tblDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Cedula", "Edad", "Telefono", "Título", "Direccion", "Sexo"
            }
        ));
        tblDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocentes);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarDActionPerformed

        DocenteDao nuevoDocente = new DocenteDao();
        String nombre = txtNombreD.getText();
        String apellido = txtApellidoD.getText();
        String cedula = txtCedulaD.getText();
        String direccion = txtDireccionD.getText();
        String telefono = txtTelefonoD.getText();
        int edad = Integer.parseInt(txtEdadD.getText());
        String titulo = (String) cmbTituloD.getSelectedItem();
        String genero = (String) cmbGeneroD.getSelectedItem();
        Docente docente = new Docente(titulo, nombre, apellido, cedula, telefono, direccion, edad, genero);
        int nD = nuevoDocente.registroDocente(docente);
        listarDocentes();
        lp.limpiarCamposTexto(jPanel3);
        lp.limpiarCamposTexto(jPanel4);


    }//GEN-LAST:event_bntGuardarDActionPerformed


    private void validarNumeros(java.awt.event.KeyEvent evt, JTextField txt) {
        char caracter = evt.getKeyChar();

        if (Character.isLetter(caracter)) {
            getToolkit().beep();
            evt.consume();
        } else if (txt.getText().length() == 10) {
            getToolkit().beep();
            evt.consume();
        }
    }


    private void txtTelefonoDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoDKeyTyped
        // TODO add your handling code here:
        validarNumeros(evt, txtTelefonoD);

    }//GEN-LAST:event_txtTelefonoDKeyTyped

    private void txtEdadDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadDKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (Character.isLetter(caracter)) {
            getToolkit().beep();
            evt.consume();
        } else if (txtEdadD.getText().length() == 2) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtEdadDKeyTyped

    private void txtCedulaDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaDKeyTyped
        // TODO add your handling code here:
        validarNumeros(evt, txtCedulaD);
    }//GEN-LAST:event_txtCedulaDKeyTyped

    private void bntActualizarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActualizarDActionPerformed
        
        if (id != 0) {
            DocenteDao nuevoDocente = new DocenteDao();
            String nombre = txtNombreD.getText();
            String apellido = txtApellidoD.getText();
            String cedula = txtCedulaD.getText();
            String direccion = txtDireccionD.getText();
            String telefono = txtTelefonoD.getText();
            int edad = Integer.parseInt(txtEdadD.getText());
            String titulo = (String) cmbTituloD.getSelectedItem();
            String genero = (String) cmbGeneroD.getSelectedItem();
            Docente update = new Docente(id, titulo, nombre, apellido, cedula, telefono, direccion, edad,  genero);
            int r = nuevoDocente.actualizarDocente(update);
            if (r > 0) {
                JOptionPane.showMessageDialog(this, "Datos Actualizados..");
                listarDocentes();
                lp.limpiarCamposTexto(jPanel3);
                lp.limpiarCamposTexto(jPanel4);
                id = 0;
            }
            id = 0;
        }


    }//GEN-LAST:event_bntActualizarDActionPerformed

    private void btnEliminarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDActionPerformed
        // TODO add your handling code here:

        if (id != 0) {
            int opc = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar '" + txtNombreD.getText() + "'?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (opc == JOptionPane.YES_OPTION) {
                Docente eliminarD = new Docente(id);
                DocenteDao.eliminarDocente(eliminarD);
                listarDocentes();
                lp.limpiarCamposTexto(jPanel3);
                lp.limpiarCamposTexto(jPanel4);
                JOptionPane.showMessageDialog(this, "Docente Eliminado.." + txtNombreD.getText());
                id = 0;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un elemento..");
            lp.limpiarCamposTexto(jPanel3);
            lp.limpiarCamposTexto(jPanel4);
            id = 0;
        }


    }//GEN-LAST:event_btnEliminarDActionPerformed

    private void btnNuevoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDActionPerformed
        // TODO add your handling code here:
        lp.limpiarCamposTexto(jPanel3);
        lp.limpiarCamposTexto(jPanel4);
        bntActualizarD.setEnabled(false);
        btnEliminarD.setEnabled(false);
        bntGuardarD.setEnabled(true);
    }//GEN-LAST:event_btnNuevoDActionPerformed

    private void tblDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocentesMouseClicked
        if (tblDocentes.getSelectedRowCount() > 0) {
            id = (int) tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 0);
            txtNombreD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 1).toString());
            txtApellidoD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 2).toString());
            txtCedulaD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 3).toString());
            txtEdadD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 4).toString());
            txtTelefonoD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 5).toString());
            cmbTituloD.setSelectedItem(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 6).toString());
            txtDireccionD.setText(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 7).toString());
            cmbGeneroD.setSelectedItem(tblDocentes.getValueAt(tblDocentes.getSelectedRow(), 9).toString());
        }
        
        bntActualizarD.setEnabled(true);
        btnEliminarD.setEnabled(true);
        bntGuardarD.setEnabled(false);

    }//GEN-LAST:event_tblDocentesMouseClicked

    private void listarDocentes() {
        DefaultTableModel dtm = (DefaultTableModel) tblDocentes.getModel();
        DocenteDao listarD = new DocenteDao();
        List<Docente> lista = listarD.listar();
        dtm.setRowCount(0);
        for (Docente docente : lista) {
            Object[] fila = new Object[]{docente.getIdDocente(),
                docente.getNombre(), docente.getApellido(), docente.getCedula(),
                docente.getEdad(), docente.getTelefono(), docente.getTitulo(),
                docente.getDireccion(), docente.getSexo()};
            dtm.addRow(fila);
        }
        bntActualizarD.setEnabled(false);
        btnEliminarD.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntActualizarD;
    private javax.swing.JButton bntGuardarD;
    private javax.swing.JButton btnEliminarD;
    private javax.swing.JButton btnNuevoD;
    private javax.swing.JComboBox<String> cmbGeneroD;
    private javax.swing.JComboBox<String> cmbTituloD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDocentes;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtCedulaD;
    private javax.swing.JTextField txtDireccionD;
    private javax.swing.JTextField txtEdadD;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtTelefonoD;
    // End of variables declaration//GEN-END:variables
}
